# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-28 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.AutoField(primary_key=True, serialize=False)),
                ('stu_name', models.CharField(db_index=True, max_length=32, unique=True)),
                ('room', models.ManyToManyField(to='model03.Room')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('stu_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=64, null=True)),
                ('no', models.CharField(max_length=128, null=True)),
                ('student', models.OneToOneField(db_column='stu_id', on_delete=django.db.models.deletion.CASCADE, to='model03.Student')),
            ],
            options={
                'db_table': 'student_detail',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tea_name', models.CharField(db_index=True, max_length=32, unique=True)),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(db_column='t_id', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='model03.Teacher'),
        ),
    ]
