# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-28 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model03', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='room',
            field=models.ManyToManyField(related_name='students', to='model03.Room'),
        ),
    ]
