# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-24 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('dept_no', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(db_index=True, max_length=15)),
                ('loc', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'dept',
            },
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('emp_no', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(db_index=True, max_length=15, unique=True)),
                ('job', models.CharField(max_length=10)),
                ('mgr', models.IntegerField(null=True)),
                ('hire_date', models.DateTimeField(auto_now_add=True)),
                ('sal', models.DecimalField(decimal_places=2, max_digits=7)),
                ('comm', models.DecimalField(decimal_places=2, max_digits=7)),
                ('dept_no', models.IntegerField()),
            ],
            options={
                'db_table': 'emp',
            },
        ),
    ]
