# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-24 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model02', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='is_delete',
            field=models.BooleanField(default=0),
        ),
    ]
