# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-29 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
    ]
